name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet pack src/PhoenixLabs.Results/PhoenixLabs.Results.csproj -c Release -o nupkgs
      
    - name: Upload NuGet package artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: nupkgs/*.nupkg
